#!/usr/bin/env bash
set -euo pipefail

WORKSPACE_ROOT="/workspaces/edu-code-course-rdb"
BASH_RC="${HOME}/.bashrc"
APPLY_CHANGES=0

START_MARKER="# >>> edu-code-course-rdb newrepo-license reminder >>>"
END_MARKER="# <<< edu-code-course-rdb newrepo-license reminder <<<"

usage() {
  cat <<'EOF'
Usage:
  bash scripts/install-newrepo-license-reminder.sh [options]

Options:
  --workspace-root <path>   Workspace root with scripts/newrepo-license
  --bashrc <path>           Bash rc target file (default: ~/.bashrc)
  --apply                   Write changes to bashrc
  --dry-run                 Show planned changes only (default)
  --help                    Show this help

What this installs:
  1) alias newrepo-license='bash <workspace>/scripts/newrepo-license'
  2) gh() wrapper that reminds after successful 'gh repo create'

After installation:
  source ~/.bashrc
EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --workspace-root)
        WORKSPACE_ROOT="${2:-}"
        shift 2
        ;;
      --bashrc)
        BASH_RC="${2:-}"
        shift 2
        ;;
      --apply)
        APPLY_CHANGES=1
        shift
        ;;
      --dry-run)
        APPLY_CHANGES=0
        shift
        ;;
      --help|-h)
        usage
        exit 0
        ;;
      *)
        echo "[newrepo-license-reminder] ERROR: unknown option: $1" >&2
        usage
        exit 1
        ;;
    esac
  done
}

validate_inputs() {
  if [[ ! -x "$WORKSPACE_ROOT/scripts/newrepo-license" ]]; then
    echo "[newrepo-license-reminder] ERROR: command not found or not executable: $WORKSPACE_ROOT/scripts/newrepo-license" >&2
    echo "[newrepo-license-reminder] HINT: make sure scripts/newrepo-license exists and has execute permission." >&2
    exit 1
  fi

  mkdir -p "$(dirname "$BASH_RC")"
  touch "$BASH_RC"
}

generate_block() {
  cat <<EOF
$START_MARKER
# Auto-generated by scripts/install-newrepo-license-reminder.sh
alias newrepo-license='bash $WORKSPACE_ROOT/scripts/newrepo-license'

gh() {
  command gh "\$@"
  local status=\$?

  if [[ \$status -eq 0 && "\${1:-}" == "repo" && "\${2:-}" == "create" ]]; then
    echo "[newrepo-license-reminder] Neues Repository erstellt. Bitte jetzt ausführen:"
    echo "  newrepo-license --owner <owner> --name <repo-name> --apply"
  fi

  return \$status
}
$END_MARKER
EOF
}

remove_existing_block() {
  local src_file="$1"
  local dst_file="$2"

  awk -v start="$START_MARKER" -v end="$END_MARKER" '
    $0 == start { skip=1; next }
    $0 == end { skip=0; next }
    !skip { print }
  ' "$src_file" >"$dst_file"
}

main() {
  parse_args "$@"
  validate_inputs

  local temp_clean
  temp_clean="$(mktemp)"

  remove_existing_block "$BASH_RC" "$temp_clean"

  if [[ $APPLY_CHANGES -eq 0 ]]; then
    echo "[newrepo-license-reminder] DRY-RUN"
    echo "[newrepo-license-reminder] Would update: $BASH_RC"
    echo "[newrepo-license-reminder] Would append block:"
    generate_block
    rm -f "$temp_clean"
    exit 0
  fi

  {
    cat "$temp_clean"
    echo
    generate_block
  } >"$BASH_RC"

  rm -f "$temp_clean"

  echo "[newrepo-license-reminder] Installed reminder in: $BASH_RC"
  echo "[newrepo-license-reminder] Activate now with: source $BASH_RC"
}

main "$@"